=== adrobisch/rmf-codegen/ctp-validators/src/main/resources/ruleset.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ruleset" type="rulesetType"/>
  <xs:complexType name="optionType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="type" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="optionsType">
    <xs:sequence>
      <xs:element type="optionType" name="option" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ruleType">
    <xs:all>
      <xs:element type="xs:string" name="name"/>
      <xs:element type="optionsType" name="options" minOccurs="0"/>
    </xs:all>
    <xs:attribute type="severity" name="severity" use="optional" default="error"/>
  </xs:complexType>
  <xs:simpleType name="severity" final="restriction" >
    <xs:restriction base="xs:string">
      <xs:enumeration value="error" />
      <xs:enumeration value="warn" />
      <xs:enumeration value="info" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="rulesType">
    <xs:sequence>
      <xs:element type="ruleType" name="rule" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="applyType">
    <xs:attribute type="xs:string" name="set" use="required"/>
  </xs:complexType>
  <xs:complexType name="rulesetType">
    <xs:all>
      <xs:element type="xs:string" name="name"/>
      <xs:element type="applyType" name="apply" minOccurs="0"/>
      <xs:element type="rulesType" name="rules"  minOccurs="0"/>
    </xs:all>
  </xs:complexType>
</xs:schema>

=== adrobisch/rmf-codegen/ctp-validators/src/main/resources/ruleset.xml
<?xml version="1.0" encoding="UTF-8" ?>
<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/commercetools/rmf-codegen/main/ctp-validators/src/main/resources/ruleset.xsd">
    <name>default</name>
    <apply set="default"/>
    <rules>
        <rule enabled="false">
            <name>com.commercetools.rmf.validators.DatetimeRule</name>
        </rule>
        <rule enabled="true">
            <name>com.commercetools.rmf.validators.BooleanPropertyNameRule</name>
        </rule>
    </rules>
</ruleset>
