=== adrobisch/rmf-codegen/tools/cli-application/src/main/resources/diff.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="diff" type="diffType"/>
  <xs:complexType name="checkType">
    <xs:sequence>
      <xs:element type="xs:string" name="name"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="checksType">
    <xs:sequence>
      <xs:element type="checkType" name="check" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="diffType">
    <xs:sequence>
      <xs:element type="xs:string" name="name"/>
      <xs:element type="checksType" name="checks"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== adrobisch/rmf-codegen/tools/cli-application/src/main/resources/diff.xml
<?xml version="1.0" encoding="UTF-8" ?>
<diff xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="diff.xsd">
    <name>default</name>
    <checks>
        <check>
            <name>io.vrap.rmf.codegen.cli.diff.PropertyRemovedCheck</name>
        </check>
        <check>
            <name>io.vrap.rmf.codegen.cli.diff.PropertyAddedCheck</name>
        </check>
        <check>
            <name>io.vrap.rmf.codegen.cli.diff.TypeRemovedCheck</name>
        </check>
        <check>
            <name>io.vrap.rmf.codegen.cli.diff.TypeAddedCheck</name>
        </check>
        <check>
            <name>io.vrap.rmf.codegen.cli.diff.MethodAddedCheck</name>
        </check>
        <check>
            <name>io.vrap.rmf.codegen.cli.diff.MethodRemovedCheck</name>
        </check>
        <check>
            <name>io.vrap.rmf.codegen.cli.diff.ResourceAddedCheck</name>
        </check>
        <check>
            <name>io.vrap.rmf.codegen.cli.diff.ResourceRemovedCheck</name>
        </check>
    </checks>
</diff>
